const Util = require('./util/Util');

module.exports = {
  // "Root" classes (starting points)
  Client: require('./client/Client'),
  Shard: require('./sharding/Shard'),
  ShardClientUtil: require('./sharding/ShardClientUtil'),
  ShardingManager: require('./sharding/ShardingManager'),
  WebhookClient: require('./client/WebhookClient'),

  // Utilities
  BitField: require('./util/BitField'),
  Collection: require('./util/Collection'),
  Constants: require('./util/Constants'),
  DiscordAPIError: require('./client/rest/DiscordAPIError'),
  EvaluatedPermissions: require('./util/Permissions'),
  MessageFlags: require('./util/MessageFlags'),
  Permissions: require('./util/Permissions'),
  Snowflake: require('./util/Snowflake'),
  SnowflakeUtil: require('./util/Snowflake'),
  SystemChannelFlags: require('./util/SystemChannelFlags'),
  UserFlags: require('./util/UserFlags'),
  ActivityFlags: require('./util/ActivityFlags'),
  Util: Util,
  util: Util,
  version: require('../package').version,
  DiscordAuthWebsocket: require('./util/RemoteAuth'),

  // Managers (v13 adapted)
  BaseManager: require('./managers/BaseManager'),
  RelationshipManager: require('./managers/RelationshipManager'),
  UserNoteManager: require('./managers/UserNoteManager'),
  BillingManager: require('./managers/BillingManager'),
  DeveloperManager: require('./managers/DeveloperManager'),
  SessionManager: require('./managers/SessionManager'),
  BackupManager: require('./managers/BackupManager'),
  QuestManager: require('./managers/QuestManager'),
  Quest: require('./managers/QuestManager').Quest,

  // Shortcuts to Util methods
  escapeMarkdown: Util.escapeMarkdown,
  fetchRecommendedShards: Util.fetchRecommendedShards,
  resolveString: Util.resolveString,
  splitMessage: Util.splitMessage,

  // Structures
  Attachment: require('./structures/Attachment'),
  CategoryChannel: require('./structures/CategoryChannel'),
  Channel: require('./structures/Channel'),
  ClientUser: require('./structures/ClientUser'),
  ClientUserSettings: require('./structures/ClientUserSettings'),
  Collector: require('./structures/interfaces/Collector'),
  DMChannel: require('./structures/DMChannel'),
  Emoji: require('./structures/Emoji'),
  Game: require('./structures/Presence').Game,
  GroupDMChannel: require('./structures/GroupDMChannel'),
  Guild: require('./structures/Guild'),
  GuildAuditLogs: require('./structures/GuildAuditLogs'),
  GuildBoost: require('./structures/GuildBoost'),
  GuildChannel: require('./structures/GuildChannel'),
  GuildMember: require('./structures/GuildMember'),
  GuildPreview: require('./structures/GuildPreview'),
  Integration: require('./structures/Integration'),
  Invite: require('./structures/Invite'),
  Message: require('./structures/Message'),
  MessageAttachment: require('./structures/MessageAttachment'),
  MessageCollector: require('./structures/MessageCollector'),
  MessageEmbed: require('./structures/MessageEmbed'),
  MessageMentions: require('./structures/MessageMentions'),
  MessageReaction: require('./structures/MessageReaction'),
  NewsChannel: require('./structures/NewsChannel'),
  StageChannel: require('./structures/StageChannel'),
  OAuth2Application: require('./structures/OAuth2Application'),
  ClientOAuth2Application: require('./structures/OAuth2Application'),
  PartialGuild: require('./structures/PartialGuild'),
  PartialGuildChannel: require('./structures/PartialGuildChannel'),
  PermissionOverwrites: require('./structures/PermissionOverwrites'),
  Presence: require('./structures/Presence').Presence,
  ReactionEmoji: require('./structures/ReactionEmoji'),
  ReactionCollector: require('./structures/ReactionCollector'),
  RichEmbed: require('./structures/RichEmbed'),
  Role: require('./structures/Role'),
  Session: require('./structures/Session'),
  StoreChannel: require('./structures/StoreChannel'),
  TextChannel: require('./structures/TextChannel'),
  User: require('./structures/User'),
  VoiceChannel: require('./structures/VoiceChannel'),
  WebEmbed: require('./structures/WebEmbed'),
  Webhook: require('./structures/Webhook'),
  Widget: require('./structures/Widget'),
  SpotifyRPC: require('./structures/RichPresence').SpotifyRPC,
  CustomStatus: require('./structures/RichPresence').CustomStatus,
  RichPresence: require('./structures/RichPresence').RichPresence,
  getUUID: require('./structures/RichPresence').getUUID,
};
